manifest:
  remotes:
    - name: ergohaven
      url-base: https://github.com/ergohaven
    - name: urob
      url-base: https://github.com/urob
    - name: d3dat
      url-base: https://github.com/d3dat
  projects:
    - name: ergohaven-zmk
      remote: ergohaven
      revision: main
      import: config/west.yml
    - name: zmk-tri-state
      remote: urob
      revision: main
    - name: zmk-lock-morph
      remote: d3dat
      revision: main
  self:
    path: config
